/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zovl_zhongguanhua_jni_demo_jni_Person */

#ifndef _Included_zovl_zhongguanhua_jni_demo_jni_Person
#define _Included_zovl_zhongguanhua_jni_demo_jni_Person
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zovl_zhongguanhua_jni_demo_jni_Person
 * Method:    getInfo
 * Signature: (Ljava/lang/String;IZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zovl_zhongguanhua_jni_demo_jni_Person_getInfo
  (JNIEnv *, jobject, jstring, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
